var index3 =
{
  "app":[
    {
      "src":"html5.jpg",
      "txt":"了然于胸的h5新标签以及js的API"
    },
    {
      "src":"css3.jpg",
      "txt":"随手拈来的css3新增动画效果让人沉迷其中"
    },
    {
      "src":"js.png",
      "txt":"扎实的js基础总是让人觉得此人靠谱"
    },
    {
      "src":"nodejs.jpg",
      "txt":"会基本的后台交互才能算得上是个前端"
    },
    {
      "src":"jquery.png",
      "txt":"阅读过部分源码的人运气不会太差"
    },
    {
      "src":"bootstrap.png",
      "txt":"一个让设计师都能做前端的优美框架"
    },
    {
      "src":"less.png",
      "txt":"突然觉得css也可以写的这么爽快"
    },
    {
      "src":"angular.jpg",
      "txt":"就像是发现了新大陆一样,对此乐不思蜀"
    },
    {
      "src":"vue.jpg",
      "txt":"强大的中文文档让我对其运用熟练"
    },
    {
      "src":"git.jpg",
      "txt":"团队协作的最佳选择"
    },
    {
      "src":"gulp.jpg",
      "txt":"让一个前端更加注重代码,而不是复杂的文件结构"
    },
    {
      "src":"react.png",
      "txt":"我当然不能止步于“做页面”,所以我掌握了它"
    }
  ]
}